import { format } from "prettier";
import parserSolidity from "prettier-plugin-solidity";

import { parseSchema } from "./schema.js";
import { version } from "./cli.js";

import {
  getStructs,
  getStorages,
  getIndexes,
  getEvents,
  getCounters,
} from "./storage/all.js";

import {
  getDeleteIndexFunctions,
  getAddIndexFunctions,
  getPopFunctions,
} from "./helpers/all.js";

import {
  getAddFunctions,
  getDeleteFunctions,
  getUpdateFunctions,
  getFieldSetFunctions,
  getFindFunctions,
  getGetFunctions,
  getFieldGetFunctions,
} from "./crud/all.js";

/**
 * Generates a complete Solidity contract with CRUD operations for a given schema.
 * @param {Object} schema - The schema object to parse.
 * @return {string} Formatted Solidity contract.
 */
export const generate = (schema, options) => {
  const parsed = parseSchema(schema);
  // Data layer
  const counters = getCounters(parsed);
  const structs = getStructs(parsed);
  const events = getEvents(parsed);
  const storages = getStorages(parsed);
  const indexes = getIndexes(parsed);
  // CRUD helpers
  const popFunctions = getPopFunctions(parsed);
  const deleteIndexFunctions = getDeleteIndexFunctions(parsed);
  const addIndexFunctions = getAddIndexFunctions(parsed);
  // CRUD functions
  const addFunctions = getAddFunctions(parsed);
  const deleteFunctions = getDeleteFunctions(parsed);
  const updateFunctions = getUpdateFunctions(parsed);
  const setFieldFunctions = getFieldSetFunctions(parsed);
  const findFunctions = getFindFunctions(parsed);
  const getFunctions = getGetFunctions(parsed);
  const getFieldFunctions = getFieldGetFunctions(parsed);

  const contract = `\
//SPDX-License-Identifier: UNLICENSED
pragma solidity ${options.solidity};

import "@openzeppelin/contracts/utils/Context.sol";
import "@openzeppelin/contracts/access/Ownable.sol";

/**
 * @title ${options.contract}
 * @notice This contract has been automatically generated by SolidQuery ${version}.
 * It represents a structured, on-chain database that includes CRUD operations, 
 * on-chain indexing capabilities, and getter and setter functions where applicable. 
 * It is tailored to a specific schema, provided as input in a YAML format.
 * For detailed function descriptions and specific structure, please refer to the function 
 * and struct level comments within the contract.
 * @dev For more information on SolidQuery, please visit our GitHub repository.
 * https://github.com/KenshiTech/SolidQuery
 */
contract ${options.contract} is Context, Ownable {
  ${structs}

  ${counters}

  ${events}

  ${storages}

  ${indexes}

  ${popFunctions}
  ${deleteIndexFunctions}
  ${addIndexFunctions}
  ${addFunctions}
  ${deleteFunctions}
  ${updateFunctions}
  ${setFieldFunctions}
  ${findFunctions}
  ${getFunctions}
  ${getFieldFunctions}
}
`;

  const formatted = format(contract, {
    parser: "solidity-parse",
    plugins: [parserSolidity],
    tabWidth: 2,
  });

  return formatted;
};
